version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: streamkit-postgres
    environment:
      POSTGRES_DB: streamkit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamkit-network

  # Go API Server (with FFmpeg for HLS encoding)
  api:
    build: .
    container_name: streamkit-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: streamkit
      RTMP_HOST: localhost
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - hls_output:/tmp/hls
    depends_on:
      - postgres
    networks:
      - streamkit-network

  # RTMP Server (Ingest Only)
  rtmp:
    build: ./internal/RTMP-server
    container_name: streamkit-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8081:80"    # HTTP port for stats and HLS playback
    volumes:
      - hls_output:/tmp/hls
    networks:
      - streamkit-network

volumes:
  postgres_data:
  hls_output:

networks:
  streamkit-network:
    driver: bridge 